### ISSUE TITLE
Treebanking

### ISSUE THREAD

**Issue by J-manning2021** [SunoikisisDC/SunoikisisDC-2021-2022#11]
So far, working on the treebanking I have found that it really does require a fuller understanding of your chosen language. Working through the Latin text, I find I'm made very aware of the gaps in my knowledge of Latin from being a bit out of practice. I can really see how it could be used in conjunction with more traditional methods of learning Latin to get a better understanding of how to really engage with texts when translating them.

**Comment by ZizhaoXU** [comment]
I am feeling the same. I just did some treebanking in Greek, which I haven't used for a long time. When I was doing it I felt that I really need to revise the Greek grammar, especially for the 'relation' part, while the 'pre-select' function helps a lot for the 'morphology' part.

**Comment by gabrielbodard** [comment]
Excellent observations, thanks. Also to note is that the "relations" used in Dependency Grammar may not be exactly the same as the grammatical terms we use in learning Greek and Latin (at least in the English tradition)—we tend to use a Constituency Grammar to describe the syntax of the language.
