### ISSUE TITLE
Problem with treebanking in Greek

### ISSUE THREAD

**Issue by ZizhaoXU** [SunoikisisDC/SunoikisisDC-2021-2022#12]
I have a small technical issue with treebanking in Greek. In the second sentence of our set text, there is a phrase of  ὑπ' αὐτῶν. When I put the text into the treebanking tool, even if I have ensured that it was pasted as plain text and no space between  ὑπ' , the tool always detects it as separate and marks this [ ' ]as a punctuation, which is meaningless and I need to adjust the xml file by myself to fix it. I am wondering if anything is wrong here.

**Comment by gabrielbodard** [comment]
No, it's just that the parser that turns your text into an XML file ready for treebanking assumes that ' is a punctuation character (as it would be in some other languages), and so erroneously tags it as such. You can either ignore it in the tree, or if you feel bold, you can edit the underlying XML yourself, as you spotted!
