### ISSUE TITLE
Verbs Lacking in Latin Treebanking

### ISSUE THREAD

**Issue by SisiXie3036** [SunoikisisDC/SunoikisisDC-2021-2022#13]
Some sentences of Phaedrus seem to lack the predicative, compared to the given sample. For instance, the text shown is "Laniger contra timens", but should there be a respondet after timens?

**Comment by lettychardon** [comment]
I was wondering how to get around instances of an implied main verb (and therefore lack of predicative) as well...!

**Comment by gabrielbodard** [comment]
I think what you want here is an artificial token (which you don't have to specify a form for—although you can; just say that it's the predicate, and then you have something to hang other dependencies from, subjects, adverbials, etc.
