### ISSUE TITLE
Problem with using existing treebank data in Latin

### ISSUE THREAD

**Issue by ZizhaoXU** [SunoikisisDC/SunoikisisDC-2021-2022#14]
I have a question about how to use existing treebank data like AGLDT.  @gabrielbodard
It seems that Dendrosearch is a tool developed only for the Greek data, so I am wondering how we can query the Latin data. I have tried to put the XML file (downloaded from https://github.com/PerseusDL/treebank_data/tree/master/v2.1/Latin/texts) into the Arethusa platform or paste their links to the platform, but then it always says 'Error creating publication (during creation of collection object):undefined method `[]' for nil:NilClass'. So I would like to know how to query the Latin data and if there is any specific tool like Dendrosearch. Thank you!

**Comment by gabrielbodard** [comment]
Tagging @polinayordanova @marjavierros @francescomambrini who may have ideas for tools to use to query the trees of the Perseus Latin Treebanks…

**Comment by marjavierros** [comment]
PML Tree Query which Francesco was presenting works with Latin, if I have understood correctly.
