### ISSUE TITLE
Uploading document to Recogito

### ISSUE THREAD

**Issue by lettychardon** [SunoikisisDC/SunoikisisDC-2021-2022#15]
Hi everyone, I am having trouble uploading any documents to recogito... They just never finalise and the upload wheel just keeps spinning... Has anyone else had this issue? And when I try and use the Perseus section of the RISE Repository I just get an error message when I select a text...

**Comment by gabrielbodard** [comment]
Sorry Letty, I just noticed this issue. Did you ever resolve it? If not, I hope you at least managed to do the part of the exercise annotating one of the existing texts that Valeria shared with us…
