### ISSUE TITLE
Problem with EpiDoc

### ISSUE THREAD

**Issue by EdenCairns** [SunoikisisDC/SunoikisisDC-2021-2022#4]
I have been working on the exercise for this week and have come across an issue.  For some of the inscriptions that I have chosen, lines end in "=".  I couldn't find this marker in the Leiden conventions, but from context, I assume that they are places where a word starts on one line and continues on the next.  Is it necessary to note this when we encode inscriptions?  If so, how should it be noted?  If not, should we eliminate the "=" in our code?

Example: 

In [hoc] l[oco] iacet
bone memorie
Bo[nifatius] q[ui] bicsit
in [h]oc sec[u]lo an=
5 nis L ueq[ui]ebit
in [p]ωce s[ub] [d]ie ((%6)) Kωl(endis) Sep=
tembre indictio=
ne [duod]ecima

**Comment by gabrielbodard** [comment]
Yes, the '=' is just a slightly different convention for '-' representing the wrap of a word over two lines, so encode it by adding `break="no"` in the `<lb/>` on the next line. And then, yes, delete the '=' from your edition.
