### ISSUE TITLE
A Small Problem with EpiDoc: the display of Greek circumflex

### ISSUE THREAD

**Issue by ZizhaoXU** [SunoikisisDC/SunoikisisDC-2021-2022#5]
I have a small problem with EpiDoc. I find that the Greek accent mark of circumflex sometimes cannot display properly and drifts away slightly from its original place. I notice that it usually happens besides or in square brackets. Is this simply a technical issue of the display, or is it possible to fix it? 
![image](https://user-images.githubusercontent.com/92321645/137762132-d80d7547-8a97-4a4a-95c6-f0f0dcb74a8d.png)

**Comment by gabrielbodard** [comment]
That does seem weird. I notice that this is only happening with circumflexes on epsilon and omicron, where Unicode (the system that defines scripts in normal fonts) doesn't expect them to be, so I suspect it's just a font not being able to handle them well. I don't have any ideas for fixing them…
