### ISSUE TITLE
Greek characters with subscript iota

### ISSUE THREAD

**Issue by lettychardon** [SunoikisisDC/SunoikisisDC-2021-2022#6]
Hi all. My computer decided to update itself last night and closed everything I had opened. Now when I look at my file in oxygen, all letters with an iota subscript just appear as little boxes. Is there someway I can reformat this or do I just need to copy paste from the online inscription again? Thank you!

**Comment by gabrielbodard** [comment]
I should have thought this is just an issue with the font (the default font in Oxygen recognises modern/monotonic Greek, but not ancient/polytonic Greek). If you go into **Options --> Preferences --> Fonts --> Editor** and select a font that you know is able to display ancient Greek properly (Palatino Linotype or Arial Unicode MS are reliable), the characters should reappear.

**Comment by lettychardon** [comment]
Great, thank you very much!

**Comment by lowriwhite** [comment]
Hi, I had the same issue! All the characters with accents or an iota subscript appeared as boxes. Changing the font fixed it for me. Thank you!
