### ISSUE TITLE
EFES server not working

### ISSUE THREAD

**Issue by zoesrowe** [SunoikisisDC/SunoikisisDC-2021-2022#7]
Hi everyone,

I know this is a bit late but I wanted to quickly run my XML through EFES tonight to make sure everything works, but my browser is 'unable to connect' to the server. I followed the video on how to set up EFES and it said it would take a while for the server to start up but it doesn't seem like it's going to at all. Is there something obvious I might be missing to make it work?

**Comment by gabrielbodard** [comment]
It's a bit hard to say without looking at it. Did you install an appropriate version of Java as per the user guide? Are you using a Windows or Mac computer? Is there an error message in the command line window, that might give us a clue?

This does occasionally happen, and the community haven't completely debugged it yet, so it's almost certainly not something you're doing wrong…

**Comment by zoesrowe** [comment]
Thank you for getting back to me! I'm using a Mac, I tried updating Java, and there wasn't an error message. From the perspective of terminal everything went well, it just isn't loading anything when I put the link into my browser. I'll try it a few more times just in case.

**Comment by gabrielbodard** [comment]
Odd. The two most common errors are (a) it not opening at all in Windows (rare), or (b) it opening fine but inscription pages throwing an error message on Mac (a bit less uncommon).

If you very much want to transform your XML files to view on the web, I'll try to come up with a workaround for you that doesn't involve EFES. (Not tonight though!)
