### ISSUE TITLE
Problem with the display of 'last recorded location' and 'repository' in EFES

### ISSUE THREAD

**Issue by ZizhaoXU** [SunoikisisDC/SunoikisisDC-2021-2022#9]
I have a question about the display of 'last recorded location' and 'repository' in EFES. 
When I tried to encode the museum that an object is now kept in, I put the information in <repository> element. However, I found out that EFES does not have such a line, and it will only display the content in `<provenance type="observed">` element in 'last recorded location'. Only when there is nothing in this element can the information in `<repository>` appear, but still in the same place, 'last recorded location', which seems not to mean entirely the same as something like 'present location' or 'repository'. I am wondering if it is normal or if it is because EFES has simplified and limited the kind of information that it can display.

**Comment by gabrielbodard** [comment]
We discussed this briefly in class yesterday, but the short answer is that not all features of EpiDoc description and history that you might want to encode will appear in any given display template in EFES (the default template is from one particular project, and so reflects their usage of EpiDoc and epigraphic display). Other templates would make different choices, and if you wanted to try a couple out, I'd be happy to show where to make the parameter changes in EFES to do so.

I believe my colleague @IreneVagionakis is working as we speak on an example template for EFES that will cater for a wider range of possible features to be displayed in the EFES default view, and with any luck that will be ported to EFES in a couple of weeks. Watch this space!

**Comment by IreneVagionakis** [comment]
Actually I added this 'sample' template to EFES a week ago, precisely with the aim of having there a default template which tries to display as many encoded (meta)data as possible. @ZizhaoXU, it would be great if you could try to display your file(s) with the latest version of EFES and let me know if the new template solves your problems or if there are some useful pieces of information that are still not displayed. Thanks!

**Comment by ZizhaoXU** [comment]
Thank you very much for the replies!@IreneVagionakis I have tried the new version of EFES, which includes more kinds of data in the display and solves this problem perfectly.
